[build]
  command = "npm run build"
  publish = "out"
  functions = "functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[dev]
  framework = "next"
  targetPort = 3000
  autoLaunch = false

[context.production.environment]
  NEXT_PUBLIC_ENV = "production"